version: '3'
services:
  postgres-comp:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}

    ports:
      - '5432:5432'
    volumes:
      - postgres-compose-volume:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${PG_DB_NAME}', '-U', '${PG_USER}']
      retries: 3
      timeout: 5s
networks:
  postgres-compose-network:
    driver: bridge
volumes:
  postgres-compose-volume:
    driver: local
