version: '3'
services:
  postgres-comp:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}

    ports:
      - 5432:5432
    volumes:
      - postgres-compose-volume:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${PG_DB_NAME}', '-U', '${PG_USER}']
      retries: 3
      timeout: 5s

  web:
    restart: always
    depends_on:
      - postgres-comp
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 8080:8080
    env_file:
      - .env
    environment:
      - PG_HOST=postgres-comp
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --encore-args="--host ${HOST} --port 8080"

networks:
  postgres-compose-network:
    driver: bridge
volumes:
  postgres-compose-volume:
    driver: local
